import { exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs";
import * as path from "path";
import { storagePut } from "./storage";
import { nanoid } from "nanoid";

const execAsync = promisify(exec);

interface GenerateImageOptions {
  prompt: string;
  aspectRatio?: "1:1" | "16:9" | "4:3" | "3:2" | "2:3" | "3:4" | "9:16" | "21:9";
  addWatermark?: boolean;
}

interface GenerateImageResult {
  imageUrl: string;
  localPath: string;
  prompt: string;
}

/**
 * Generate an AI influencer image using MiniMax API via MCP
 */
export async function generateInfluencerImage(
  options: GenerateImageOptions
): Promise<GenerateImageResult> {
  const { prompt, aspectRatio = "3:4", addWatermark = false } = options;

  // Create temp directory for output
  const outputDir = `/tmp/ai-influencer-${Date.now()}`;
  await fs.promises.mkdir(outputDir, { recursive: true });

  try {
    // Build MCP command for MiniMax text_to_image
    const mcpInput = JSON.stringify({
      prompt: prompt,
      aspect_ratio: aspectRatio,
      n: 1,
      prompt_optimizer: true,
      output_directory: outputDir,
      model: "image-01",
    });

    console.log("[ImageGen] Calling MiniMax text_to_image with prompt:", prompt.substring(0, 100) + "...");

    // Execute MCP command
    const { stdout, stderr } = await execAsync(
      `manus-mcp-cli tool call text_to_image --server minimax --input '${mcpInput.replace(/'/g, "'\\''")}'`,
      { timeout: 120000 } // 2 minute timeout
    );

    console.log("[ImageGen] MiniMax response:", stdout);
    if (stderr) {
      console.warn("[ImageGen] MiniMax stderr:", stderr);
    }

    // Find the generated image file
    const files = await fs.promises.readdir(outputDir);
    const imageFile = files.find(f => f.endsWith(".png") || f.endsWith(".jpg") || f.endsWith(".jpeg"));

    if (!imageFile) {
      throw new Error("No image file generated by MiniMax");
    }

    const localPath = path.join(outputDir, imageFile);
    let imageBuffer = await fs.promises.readFile(localPath);

    // Add watermark if needed (for free tier)
    if (addWatermark) {
      imageBuffer = await addWatermarkToImage(imageBuffer);
    }

    // Upload to S3
    const fileKey = `generations/${nanoid()}-${Date.now()}.png`;
    const { url: imageUrl } = await storagePut(fileKey, imageBuffer, "image/png");

    console.log("[ImageGen] Image uploaded to S3:", imageUrl);

    return {
      imageUrl,
      localPath,
      prompt,
    };
  } catch (error) {
    console.error("[ImageGen] Error generating image:", error);
    throw error;
  } finally {
    // Cleanup temp directory
    try {
      await fs.promises.rm(outputDir, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
  }
}

/**
 * Add watermark to image buffer using ImageMagick
 */
async function addWatermarkToImage(imageBuffer: Buffer): Promise<Buffer> {
  const tempInput = `/tmp/watermark-input-${Date.now()}.png`;
  const tempOutput = `/tmp/watermark-output-${Date.now()}.png`;

  try {
    await fs.promises.writeFile(tempInput, imageBuffer);

    // Use ImageMagick to add diagonal watermark text
    const watermarkText = "AI Influencer Generator";
    const command = `convert ${tempInput} \
      -gravity center \
      -font DejaVu-Sans-Bold \
      -pointsize 48 \
      -fill "rgba(255,255,255,0.3)" \
      -annotate 45 "${watermarkText}" \
      -annotate -45 "${watermarkText}" \
      ${tempOutput}`;

    await execAsync(command);

    const watermarkedBuffer = await fs.promises.readFile(tempOutput);
    return watermarkedBuffer;
  } catch (error) {
    console.warn("[ImageGen] Watermark failed, returning original:", error);
    return imageBuffer; // Return original if watermark fails
  } finally {
    // Cleanup
    try {
      await fs.promises.unlink(tempInput);
      await fs.promises.unlink(tempOutput);
    } catch {
      // Ignore cleanup errors
    }
  }
}

/**
 * Build a detailed prompt from character settings
 */
export function buildPromptFromSettings(settings: {
  characterType: string;
  gender: string;
  ethnicity: string;
  eyeColor: string;
  skinTone: string;
  skinFeatures: string[];
  age: number;
  customPrompt?: string;
}): string {
  const {
    characterType,
    gender,
    ethnicity,
    eyeColor,
    skinTone,
    skinFeatures,
    age,
    customPrompt,
  } = settings;

  let prompt = `A photorealistic portrait of a ${age}-year-old ${gender.toLowerCase()} `;

  // Add character type specific details
  if (characterType.toLowerCase() === "human") {
    prompt += `${ethnicity.toLowerCase()} person `;
  } else {
    prompt += `${characterType.toLowerCase()} character with ${ethnicity.toLowerCase()} features `;
  }

  prompt += `with ${eyeColor.toLowerCase()} eyes and ${skinTone.toLowerCase()} skin tone`;

  // Add skin features
  if (skinFeatures && skinFeatures.length > 0 && !skinFeatures.includes("none")) {
    const features = skinFeatures.filter(f => f.toLowerCase() !== "none").join(", ");
    if (features) {
      prompt += `, featuring ${features}`;
    }
  }

  prompt += ". ";

  // Add custom prompt if provided
  if (customPrompt && customPrompt.trim()) {
    prompt += customPrompt.trim() + ". ";
  }

  // Add quality modifiers
  prompt += "Professional influencer photo, high quality, studio lighting, social media ready, Instagram aesthetic, fashion photography style, 8K resolution, detailed skin texture, natural makeup, confident expression.";

  return prompt;
}
